name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 18
      uses: actions/setup-java@v4
      with:
        java-version: '18'
        distribution: 'temurin'
        cache: gradle

    - name: Install Android SDK
      uses: android-actions/setup-android@v2
      
    - name: Decode google-services.json
      run: echo "${{ secrets.FIREBASE_CONFIG }}" | base64 -d > code/app/google-services.json

    - name: Grant execute permission for gradlew
      run: chmod +x code/gradlew
    - name: Build with Gradle
      working-directory: code
      run: ./gradlew build
